### ISSUE TITLE
Variable 'dailyrainin' never resets

### ISSUE THREAD

**Issue by georgep56** [sparkfun/Photon_Weather_Shield#10]
I'm new to GitHub so I'm sorry if I'm not following protocol ;-)

In the file 'SparkFun_Photon_Weather_Basic_Soil_Meters.ino' I've noticed that the value 'dailyrainin' (rain inches so far today in local time) never gets reset. I've made this small addition to my code towards the bottom of 'loop()':

```
    currentTime = Time.now();

    if ((Time.hour(currentTime) == 0) && (Time.minute(currentTime) == 0) && (Time.second(currentTime) == 0)){
        DailyRainIn = 0;
    }
```

**Comment by jim-c-sims** [comment]
I noticed the same thing. I'm guessing that I need to add an I2C real time clock. Is that what you did?

**Comment by georgep56** [comment]
Yes, my hardware comprised an arduino and an i2c rtc so had access to the time of day.

**Comment by wmjenk** [comment]
Note that the method George used gets current UTC time and would need to be corrected for your time zone if you want to reset at midnight local time. Note also that the UTC time does not adjust for daylight savings time. George’s code works fine with the photon and the weather shield just adjust for your time zone.

Bill

**Comment by santaimpersonator** [comment]
This product has been retired for some time now and this issue hasn't been addressed for a while. I am closing this issue before archiving the repo.
