### ISSUE TITLE
Wind Direction changes needed if you plan to upload to Weather Underground

### ISSUE THREAD

**Issue by wmjenk** [sparkfun/Photon_Weather_Shield#11]
Note that "winddir" in the sample code is parsed by the value of the ADC ranges into eight integers 0-7 representing N,NE,E,SE,S,SW,W,NW. The sample code then uses these 0-7 integers to select the correct direction text to output to the serial line. However Weather Underground is expecting "winddir" to be an integer between 0-360 representing a direction in degrees. A simple solution is to replace the integers 0-7 in the get_wind_direction with the direction in degrees, 0, 45, 90,135,180,225,270,315. The same directional integer values can be substituted for the 0-7 values in the serial print routine. Note also that the get_wind_direction routine returns a "-1" if it fails to return one of the defined adc range values. This is a problem for Weather Underground as a -1 is considered an inappropriate value for wind direction and the site will be flagged for reporting inaccurate data. You should avoid uploading any wind directional data values outside the 0-360 range to Weather Underground.

**Comment by santaimpersonator** [comment]
This product has been retired for some time now and this issue hasn't been addressed for a while. I am closing this issue before archiving the repo.
