### ISSUE TITLE
Tutorial Mismatch

### ISSUE THREAD

**Issue by bjohnsonmn** [sparkfun/Photon_Weather_Shield#13]
When (As a Noob), I follow the instruction on the SparkFun website, there is a mismatch in what I expect to see.

SparkFun's Tutorial indicates I should find code like this:

/////////////////////////PHANT STUFF///////////////
const char server[] = "data.sparkfun.com";
const char publicKey[] = "yourPublicKey";
const char privateKey[] = "yourPrivateKey";
Phant phant(server, publicKey, privateKey);
//////////////////////////////////////

I am aware that the placeholder text is to be replaced.

I made the replacements in the section starting on line 25 (26, 27,28).  This is the result I get when I run a compile in the online IDE:

SparkFun_Photon_Weather_Shield_Library/SparkFun_Photon_Weather_Shield_Library.cpp: In member function 'float Weather::readPressure()':
SparkFun_Photon_Weather_Shield_Library/SparkFun_Photon_Weather_Shield_Library.cpp:320:22: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  if(IIC_Read(STATUS) & (1<<2) == 0) toggleOneShot(); //Toggle the OST bit causing the sensor to immediately take another reading
                      ^
SparkFun_Photon_Weather_Shield_Library/SparkFun_Photon_Weather_Shield_Library.cpp:324:25: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  while(IIC_Read(STATUS) & (1<<2) == 0)
                         ^
SparkFun_Photon_Weather_Shield_Library/SparkFun_Photon_Weather_Shield_Library.cpp: In member function 'float Weather::readBaroTemp()':
SparkFun_Photon_Weather_Shield_Library/SparkFun_Photon_Weather_Shield_Library.cpp:360:22: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  if(IIC_Read(STATUS) & (1<<1) == 0) toggleOneShot(); //Toggle the OST bit causing the sensor to immediately take another reading
                      ^
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::Phant(String, String, String)':
SparkFunPhant/SparkFunPhant.cpp:25: multiple definition of `Phant::Phant(String, String, String)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:30: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::Phant(String, String, String)':
SparkFunPhant/SparkFunPhant.cpp:25: multiple definition of `Phant::Phant(String, String, String)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:30: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, String)':
SparkFunPhant/SparkFunPhant.cpp:32: multiple definition of `Phant::add(String, String)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:37: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, char)':
SparkFunPhant/SparkFunPhant.cpp:39: multiple definition of `Phant::add(String, char)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:44: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, int)':
SparkFunPhant/SparkFunPhant.cpp:46: multiple definition of `Phant::add(String, int)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:51: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, unsigned char)':
SparkFunPhant/SparkFunPhant.cpp:53: multiple definition of `Phant::add(String, unsigned char)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:58: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, long)':
SparkFunPhant/SparkFunPhant.cpp:60: multiple definition of `Phant::add(String, long)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:65: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, unsigned int)':
SparkFunPhant/SparkFunPhant.cpp:66: multiple definition of `Phant::add(String, unsigned int)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:71: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, unsigned long)':
SparkFunPhant/SparkFunPhant.cpp:72: multiple definition of `Phant::add(String, unsigned long)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:77: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, double, unsigned int)':
SparkFunPhant/SparkFunPhant.cpp:78: multiple definition of `Phant::add(String, double, unsigned int)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:83: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::add(String, float, unsigned int)':
SparkFunPhant/SparkFunPhant.cpp:85: multiple definition of `Phant::add(String, float, unsigned int)'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:90: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::queryString()':
SparkFunPhant/SparkFunPhant.cpp:92: multiple definition of `Phant::queryString()'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:97: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::url()':
SparkFunPhant/SparkFunPhant.cpp:96: multiple definition of `Phant::url()'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:101: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::get()':
SparkFunPhant/SparkFunPhant.cpp:107: multiple definition of `Phant::get()'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:112: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::post()':
SparkFunPhant/SparkFunPhant.cpp:117: multiple definition of `Phant::post()'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:122: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::clear()':
SparkFunPhant/SparkFunPhant.cpp:133: multiple definition of `Phant::clear()'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:138: first defined here
../../../build/target/user/platform-6/libuser.a(SparkFunPhant.o): In function `Phant::particlePost()':
SparkFunPhant/SparkFunPhant.cpp:144: multiple definition of `Phant::particlePost()'
../../../build/target/user/platform-6/libuser.a(weatheronlinesimple1.o):weatheronlinesimple1.cpp:149: first defined here
collect2: error: ld returned 1 exit status
make: *** [69df6f089b6a2ca2c5f74458a1bca8b479eef178bb9fdd69c4e20aa2cca0.elf] Error 1
Error: Could not compile. Please review your code.

**Comment by JoelEB** [comment]
Hi, this portion of the code has been tested and works. Your issue looks to be library related. Please ensure you have all the correct libraries included for use in the online Particle IDE.
