### ISSUE TITLE
Windspeedmph step function

### ISSUE THREAD

**Issue by hartmms** [sparkfun/Photon_Weather_Shield#14]
I modified the X to post several variables up to Weather Underground. I'm noticing the windspeedmph variable has very few values: 0, 7.2, 14.5, etc.  Is anyone else noticing the same thing?

**Comment by cwrisley** [comment]
yes, I noticed the same thing (sort of)
I added 
Spark.publish("Wind Speed", String(windspeedmph) + "mph");
delay(2000);
So I could monitor the figures on that I was uploading, and I see alot of this:
{"data":"3.926316mph","ttl":"60","published_at":"2016-03-14T00:29:14.482Z","coreid":"XXXXXXXXX","name":"Wind Speed"}
{"data":"3.905759mph","ttl":"60","published_at":"2016-03-14T00:30:26.544Z","coreid":"XXXXXXXXX","name":"Wind Speed"}
{"data":"7.852632mph","ttl":"60","published_at":"2016-03-14T00:28:01.617Z","coreid":"XXXXXXXXX","name":"Wind Speed"}

Summary: they are "different" numbers, but they seem to close to be true...

**Comment by hartmms** [comment]
What frequency are you  calling the "getWeather()"  function. That's the one that actually sets that variable. 

Looking at the code closer, the "loop" runs every second and always calls get_wind_speed before "getWeather()":
```
currentSpeed = get_wind_speed()
.
.
.
if (count == X) {
  getWeather()
    windspeedmph = get_wind_speed()
```

So the windspeedmph variable really isn't much different than "currentSpeed". Also note the 2nd call to "get_wind_speed" happens as fast as the code can execute the stuff in between (and other system tasks). I'll bet this elapsed time is so small there are very few windIRQs, causing the step function we see. I'll change my code to post "currentSpeed", which would allow the windIRQ to have a full second of counts to calculate from. Maybe that would result in something better.

**Comment by cwrisley** [comment]
Not going to lie, I'm very new to this (aka this is my first ever project of any sort), I'll try to answer... I started with the code posted here on github, but really did alot of commenting it out to get it to post "some" data to wunderground (still working on other fields (windgust etc...http://www.wunderground.com/personal-weather-station/dashboard?ID=KNYESSEX3#history), so I'll try to answer.

I think this answers your question:

 getWeather();
    //Rather than use a delay, keeping track of a counter allows the photon to
    // still take readings and do work in between printing out data.
    count++;
    //alter this number to change the amount of time between each reading
    if(count == 5)
    {
       printInfo();
       count = 0;
       
    //Send data to Weather Underground
        sendToWU();
    }
  }

I do recall having to mess around and getting errors when trying to save around current speed and wind speed, I might have switched them around at some point....

int WDIR = A0;
int RAIN = D2;
int WSPEED = D3;
int currentTime = 0;

//Global Variables
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
long lastSecond; //The millis counter to see when a second rolls by
byte seconds; //When it hits 60, increase the current minute
byte seconds_2m; //Keeps track of the "wind speed/dir avg" over last 2 minutes array of data
byte minutes; //Keeps track of where we are in various arrays of data
byte minutes_10m; //Keeps track of where we are in wind gust/dir over last 10 minutes array of data

int winddir = 0; // [0-360 instantaneous wind direction]
float windspeedmph = 0; // [mph instantaneous wind speed]
float windgustmph = 0; // [mph current wind gust, using software specific time period]
int windgustdir = 0; // [0-360 using software specific time period]
float windspdmph_avg2m = 0; // [mph 2 minute average wind speed mph]
int winddir_avg2m = 0; // [0-360 2 minute average wind direction]
float windgustmph_10m = 0; // [mph past 10 minutes wind gust mph ]
int windgustdir_10m = 0; // [0-360 past 10 minutes wind gust direction]
float rainin = 0; // [rain inches over the past hour)] -- the accumulated rainfall in the past 60 min
long lastWindCheck = 0;
volatile float dailyrainin = 0; // [rain inches so far today in local time]
volatile long lastWindIRQ = 0;
volatile byte windClicks = 0;
volatile unsigned long raintime, rainlast, raininterval, rain;
float humidity = 0;
float tempf = 0;
float tempc = 0;
//double InTempC = 0;//original temperature in C from DS18B20
//float soiltempf = 0;//converted temperature in F from DS18B20
float dewptc = 0;
float dewptF = 0;
float dewptf = 0;
float dewptC = 0;
float tempC = 0; 
float pascals = 0;
float altf = 0;
float baroTemp = 0;
//int soilMoisture = 0;
float humTempF = 0;  //humidity sensor temp reading, fahrenheit
float humTempC = 0;  //humidity sensor temp reading, celsius
float baroTempF = 0; //barometer sensor temp reading, fahrenheit
float baroTempC = 0; //barometer sensor temp reading, celsius
float inches = 0;

int count = 0;

void wspeedIRQ()
// Activated by the magnet in the anemometer (2 ticks per rotation), attached to input D3
{
  if (millis() - lastWindIRQ > 10) // Ignore switch-bounce glitches less than 10ms (142MPH max reading) after the reed switch closes
  {
    lastWindIRQ = millis(); //Grab the current time
    windClicks++; //There is 1.492MPH for each click per second.
  }
}

________________

**Comment by hartmms** [comment]
Thanks for the input, but I'm not sure that will fix the issue. Based on my testing, I'm pretty sure it's the 2nd call to get_wind_speed() so close to the original call that leaves nearly zero time for "windIRQ" to trigger and generate any meaningful samples. 

I re-worked the loop() body to only get the wind speed every 5 seconds. This means I removed the "get_wind_speed" from getWeather() also. Some debug publish events later, and I can see much more realistic wind measurements. No more step function! 

Unfortunately, I've added so much of my own custom code that submitting a pull request is no longer appropriate. 

However, here is a sample of the new wind measurement part of my loop():

```
    long now = Time.now();
    hour = Time.hour(now);
    minute = Time.minute(now);
    second = Time.second(now);
    // If a new day, reset vars that keep the daily totals
    if (hour == 0 && minute == 0 && second == 0) {
      dailyrainin = 0;
      windgustmph = 0;
    }
    //Calc the wind speed every 5 seconds
    if ((second+1) % 5 == 0) {
      currentSpeed = get_wind_speed();
      int currentDirection = get_wind_direction();
      windspdavg[seconds_2m] = (int)currentSpeed;
      winddiravg[seconds_2m] = currentDirection;
      //Check to see if this is a gust for the minute
      if (currentSpeed > windgust_10m[minutes_10m]) {
        windgust_10m[minutes_10m] = currentSpeed;
        windgustdirection_10m[minutes_10m] = currentDirection;
      }
      //Check to see if this is a gust for the day
      if (currentSpeed > windgustmph) {
        windgustmph = currentSpeed;
        windgustdir = currentDirection;
      }
    }
```

I'm now using the currentSpeed variable to post the WU value of "windspeedmph". Be sure to remove the winddir, windspeedmph, windgustmph, windgustdir from the getWeather() function.

**Comment by gringofr** [comment]
hello hartmms,
It has been several weeks since I have broken my head with the code for my weather station, will you be kind enough to share your code which looks functional.

thank you in advance

**Comment by santaimpersonator** [comment]
This product has been retired for some time now and this issue hasn't been addressed for a while. I am closing this issue before archiving the repo.
