### ISSUE TITLE
rain sensor triggers incorrectly

### ISSUE THREAD

**Issue by hartmms** [sparkfun/Photon_Weather_Shield#15]
Anyone else seeing the rain IRQ trigger incorrectly? I see the code has some basic debounce code to it, so I doubt that's the issue.  Is the sensor that sensitive to vibration/high wind gusts?

**Comment by santaimpersonator** [comment]
This product has been retired for some time now and this issue hasn't been addressed for a while. I am closing this issue before archiving the repo.
