### ISSUE TITLE
Does not work with negative temperatures on 32-bit processors

### ISSUE THREAD

**Issue by jkardach** [sparkfun/Photon_Weather_Shield#16]
Hi,
On an ARM processor the temperature is not converted from the two byte registers into a float correctly and the sign is not extended resulting in a large positive number when the temperature goes below zero.
The issue occurs in the rawToCelisius method, where it a sixteen bit integer into a four byte float.  I'm guessing the casting of the 16-bit integer raw to a float must first cast to a 4 byte integer without sign-extending the upper two bytes, which then results in a larger positive integer (versus a small negative integer) before it is converted to a float.

// convert from raw to Celsius
float DallasTemperature::rawToCelsius(int16_t raw)
{
    if (raw <= DEVICE_DISCONNECTED_RAW)
        return DEVICE_DISCONNECTED_C;
    // C = RAW/128
    return (float)raw \* 0.0078125;
}

I was able to get negative results by doing the following:

```
    int temp4 = RAW;      // on ARM this is a 4byte integer, upper two bytes zero
if (RAW&0x8000) {    // check high bit of RAW to see if negative
    temp4 = temp4 | 0xFFFF0000;    // sign extend to upper 2 bytes for negative
} else {
    temp4 = temp4 & 0x0000FFFF;  // sign extend to upper 2 bytes for positive
}
    return (float) temp4* 0.0078125;        // convert to floating
```

I'm not a a great programmer, but I figure someone who is can update the library so that it will work properly on 32-bit, 16-bit and 8-bit processors.

thanks,
Jim Kardach

**Comment by santaimpersonator** [comment]
This product has been retired for some time now and this issue hasn't been addressed for a while. I am closing this issue before archiving the repo.
