### ISSUE TITLE
v11 checklist issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/Photon_Weather_Shield#18]
(1) The "SDA" trace is exposed by the tSTOP of R5. The trace could be moved down to eliminate excessive tSTOP related trace exposure.

(2) The "3.3V" trace is exposed by pin 4 of the MPL. The trace could be moved down to eliminate excessive tSTOP related trace exposure.

(3) It looks like the Si7021 package is missing tSTOP for the center pad, but does have a tCREAM polygon. As it stands, it looks like we will be pasting onto mask where the center pad will should be. This is also present in the Weather Shield which uses the same package.

**Comment by JoelEB** [comment]
Fixed tSTOP of 1) and 2). 

Added tSTOP to Si7021 footprint in parts library, Updated part on both this board as well as the Arduino Weather Shield. Rev.
