### ISSUE TITLE
Double check v11

### ISSUE THREAD

**Issue by edspark** [sparkfun/Photon_Weather_Shield#19]
1) Are any jumpers labeled clearly by their function and possible settings? [YES]
comment: SJ3 Jumper has a spelling error "dissconnect" instead of "disconnect".

2) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [YES]
comment: Missing CONN-09696 on the BOM and CONN-13002 is on the Sparkle Page but not on the BOM

3) Does it pass SparkFun DRC? [NO]
comment: No but we cruised through all 250+ errors and it's cool Joel.

4) Do all footprints have 0.008 inch silk footprint? [NO]
comment: Nope but its cool.

5) Is the polarity label outside of the package for visibility after part population? [NO]
comment: NO but it's cool.

6) The values for Diodes D8, D10, and D6 overlap nearby nets!

**Comment by JoelEB** [comment]
Pete - What do you mean by "CONN-13002 is on the Sparkle Page but not on the BOM" I see it in the BOM in Sparkle. They've been building them correctly thus far, so I'm assuming it's correct. 

Fixed issue 1 and 6. Discussed issues 3, 4 and 5 with Pete in person. 

Closing.
