### ISSUE TITLE
sensors is wrong, does not compile for 6 ino files 

### ISSUE THREAD

**Issue by hanscees** [sparkfun/Photon_Weather_Shield#20]
hi

sensors.begin();
does not compile. 
all sensorS should be sensor. S is wrong. Error introduced with soil temperature code 

this error is in all ino files made 11 months ago. Took me a while to find it.

**Comment by santaimpersonator** [comment]
This product has been retired for some time now and this issue hasn't been addressed for a while. I am closing this issue before archiving the repo.
