### ISSUE TITLE
Arduino & photon weather shield

### ISSUE THREAD

**Issue by WillemSpectrum** [sparkfun/Photon_Weather_Shield#22]
Are you somehow able to hook up the sparkfun photon weather shield to an arduino genuino uno?

Thanks in advance

**Comment by JoelEB** [comment]
Hi, If you're looking for something that will fit on an Uno, check out our[ Arduino Weather Shield](https://www.sparkfun.com/products/13956). It is very similar to the Photon Weather Shield.

**Comment by WillemSpectrum** [comment]
@JoelEB alright thank you, i think me and my classmate have made the wrong purchase then.
